### ISSUE TITLE
Att stänga av mortgage borde även stänga av säljning av rutor.

### ISSUE THREAD

**Issue by EndyMc** [EdwardKN/Monopoly#106]
Jag tycker att man inte borde få sälja rutor alls ifall man inte får inteckna dem. Detta kan dock även läggas till som ytterliggare en regel, likt så som vi har gjort med fri parkering.

**Comment by EdwardKN** [comment]
Vad ska man göra när man har negativa pengar då? Då kan man inte sälja något

**Comment by EndyMc** [comment]
Resultatet blir att det blir kortare spel. Försten att gå bankrutt förlorar.
