### ISSUE TITLE
Stängs ner ibland, inte ibland

### ISSUE THREAD

**Issue by EndyMc** [EdwardKN/Monopoly#118]
**Förklara buggen**
Kortet som är uppe på skärmen stängs **inte** ner när man intecknar en ruta, dock gör den det när man köper tillbaka rutan.

**Hur det borde fungera**
Den borde antingen alltid stänga ner eller aldrig stänga ner.

**Comment by EdwardKN** [comment]
Har aldrig sett detta problemet och lyckas inte återskapa det
