### ISSUE TITLE
Live versionen av spelet laddar ej

### ISSUE THREAD

**Issue by EndyMc** [EdwardKN/Monopoly#12]
Uncaught DOMException: CanvasRenderingContext2D.drawImage: Passed-in image is "broken" game.js:90
    drawRotatedImage https://edwardkn.github.io/Monopoly/game.js:90
    drawIsometricImage https://edwardkn.github.io/Monopoly/game.js:163
    draw https://edwardkn.github.io/Monopoly/game.js:1033
    update https://edwardkn.github.io/Monopoly/game.js:1019
    update https://edwardkn.github.io/Monopoly/game.js:371
    forEach self-hosted:203
    update https://edwardkn.github.io/Monopoly/game.js:371
    update https://edwardkn.github.io/Monopoly/game.js:279
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270
    (Async: FrameRequestCallback)
    update https://edwardkn.github.io/Monopoly/game.js:270

**Comment by EdwardKN** [comment]
solved

**Comment by EndyMc** [comment]
Samma problem kommer upp igen då den inte verkar ha vissa filer
![image](https://user-images.githubusercontent.com/82646131/232023190-65cb270b-0927-458b-bb9e-8b58f946c68c.png)
