### ISSUE TITLE
Inte säker på om detta är fixat än, Rendering konstig

### ISSUE THREAD

**Issue by EndyMc** [EdwardKN/Monopoly#21]
När en spelare är längre upp på skärmen jämfört med en annan så ska den förstnämnda vara längre bak (rendera före) för att ge 3d effekten, dock är det inte så i nuläget.

**Comment by EdwardKN** [comment]
det är fixat i vissa fall, inte alla

**Comment by EndyMc** [comment]
Jag skulle gissa att det funkar som det ska i vissa fall, då den förmodligen renderar spelarna i ordningen som de finns i _players_-listan. Inte enligt var de är på skärmen.
