### ISSUE TITLE
Tågstation ger 50kr trots att bara en ägs

### ISSUE THREAD

**Issue by EndyMc** [EdwardKN/Monopoly#37]
**Förklara buggen**
Spelare 1 köpte  södra tågstationen, spelare 2 hamnade därpå och betalade 50kr istället för 25kr som det ska vara. Det är även inconsistent mellan två klienter trots att båda har samma version (Den som finns i master)

**Hur man återskapar buggen**
Steg för att återskapa buggen:
Klicka på "kasta tärning", ha tur och landa på tågstation,
Byt spelare.
Klicka på "kasta tärning", ha otur och landa på tågstation.

**Browser :**
Chrome, Firefox, Opera, osv. Firefox är den enda som vi aktivt försöker få 100% support till.

**Comment by EdwardKN** [comment]
För mig är det 25kr exakt som det ska vara

**Comment by EdwardKN** [comment]
Buggen verkar inte existera
