### ISSUE TITLE
Fri parkering verkar inte ha någon användning

### ISSUE THREAD

**Issue by EndyMc** [EdwardKN/Monopoly#4]
Fri parkering ska ge spelaren som hamnar där alla pengar som tas från spelare via skatt, mm.

**Comment by EdwardKN** [comment]
Eftersom detta inte är en officiell monopolregel så ska detta endast finnas som en game option när man startar ett game. Det är något som ska läggas till senare.

**Comment by EndyMc** [comment]
Låter bra
