### ISSUE TITLE
Kort

### ISSUE THREAD

**Issue by EndyMc** [EdwardKN/Monopoly#41]
**Förklara buggen**
Om man trycker på ESC så kan man stänga ner när man har ett kort uppe på skärm och har alternativet att köpa/auktionera. Det finns inget som visar att man ska trycka på det för att stänga ner och det finns inget kryss att stänga ner med.

**Hur man återskapar buggen**
Steg för att återskapa buggen:
1. Gå till en köpbar ruta
2. Få kort på skärmen
3. Tryck på ESC
4. Se error

**Hur det borde fungera**
Borde antingen tas bort eller så borde det läggas till ett kryss i GUI:n

**Browser :**
Firefox

**Comment by EdwardKN** [comment]
Man ska faktiskt inte ens kunna trycka på escape i det tillfället. Min plan är att göra så att om man trycker utanför rutan så försvinner den istället för att ha en keybind som inte förklaras.
