### ISSUE TITLE
Ingen ram

### ISSUE THREAD

**Issue by EndyMc** [EdwardKN/Monopoly#53]
**Förklara buggen**
Dessa property-bilderna verkar inte ha någon ram när de är disabled

**Hur man återskapar buggen**
Steg för att återskapa buggen:
1. Gå till tradingmenyn i online-mode

**Skärmbilder**
![image](https://user-images.githubusercontent.com/82646131/234783910-65d5411e-e9a8-4ed8-88ad-3a044392b6be.png)

**Browser :**
Firefox, dock kvittar det här

**Comment by EdwardKN** [comment]
de saknar textur

**Comment by EdwardKN** [comment]
fixad
