### ISSUE TITLE
Desto längre spelarnamn, desto mindre storlek på pengatext

### ISSUE THREAD

**Issue by EndyMc** [EdwardKN/Monopoly#56]
**Förklara buggen**
Desto längre en spelares namn, desto mindre är font-size för pengatexten.

**Hur man återskapar buggen**
1. Välj ett långt namn
2. Välj ett kort namn

**Hur det borde fungera**
Samma stolek på pengatext

**Skärmbilder**
![image](https://user-images.githubusercontent.com/82646131/234846603-1152bc18-1085-44e4-8d21-42488144b4ab.png)

**Browser :**
Firefox

**Comment by EdwardKN** [comment]
fixad

**Comment by EndyMc** [comment]
Inte fixad...
![image](https://user-images.githubusercontent.com/82646131/235082100-7b889360-0b2f-452d-bc38-73dacfa9dac2.png)

**Comment by EndyMc** [comment]
btw, spelarnamnen borde ha en maxlängd på typ 70% av playerbordern

**Comment by EdwardKN** [comment]
Du har skickat in ett för långt namn. Jag har satt en maxlängd på 10 bokstäver. Den ska dock ökas lite
