### ISSUE TITLE
.

### ISSUE THREAD

**Issue by EndyMc** [EdwardKN/Monopoly#57]
**Förklara buggen**
Lots and lots of errors

**Hur man återskapar buggen**
Gjorde en auktion, tror detta hände efter det

**Skärmbilder**
![image](https://user-images.githubusercontent.com/82646131/234847124-4c22c410-f8a7-4b9c-b47b-e538babd010f.png)

**Browser :**
Firefox

**Comment by EdwardKN** [comment]
fixad
