### ISSUE TITLE
Cursor visas som pointer hela tiden

### ISSUE THREAD

**Issue by EdwardKN** [EdwardKN/Monopoly#68]
**Förklara buggen**
Cursor visas som pointer i online hela tiden

**Hur man återskapar buggen**
Spela online

**Comment by EndyMc** [comment]
Det är något i din kod, jag har inte rört cursor funktionen alls.

Om det inte är så att den kräver att man anropar den efter man gömmer knappar

**Comment by EdwardKN** [comment]
Cursor visas endast om man hoverar en synlig knapp. Det måste vara något med att en knapp som inte längre är synlig för att den inte ritad fortfarande har taggen visible och hover.
