### ISSUE TITLE
Trade av intecknade rutor

### ISSUE THREAD

**Issue by EndyMc** [EdwardKN/Monopoly#90]
**Förklara buggen**
Man kan tradea intecknade rutor, detta känns inte som att det borde kunna göras.

**Hur man återskapar buggen**
Steg för att återskapa buggen:
1. Köp en ruta
2. Inteckna den
3. Öppna en trade och ge den till en annan spelare

**Hur det borde fungera**
Inte kunna tradea intecknade rutor, eller visa i trade att en ruta är intecknad.

**Browser :**
Firefox

**Övrigt**
Efter man tradeat rutan till den andra spelaren så kan den köpa tillbaka rutan, detta ger att pengaanimationen visar 10 decimaler, trots att den bara ska visa heltal.

**Comment by EdwardKN** [comment]
Man ska kunna göra det. 
Officiell regel: "The owner may sell this mortgaged property to another player at any agreed price. If you are the new owner, you may lift the mortgage at once if you wish by paying off the mortgage plus 10% interest to the Bank."

https://www.officialgamerules.org/monopoly

**Comment by EndyMc** [comment]
> Efter man tradeat rutan till den andra spelaren så kan den köpa tillbaka rutan, detta ger att pengaanimationen visar 10 decimaler, trots att den bara ska visa heltal.

Detta är dock fortfarande en bugg
