### ISSUE TITLE
Inga knappar på köpkort

### ISSUE THREAD

**Issue by EndyMc** [EdwardKN/Monopoly#94]
**Förklara buggen**
Spelare 2 fick upp ett kort, dock kunde den inte köpa då kortet inte innehöll några knappar

**Hur man återskapar buggen**
Spelade ett varv, där det fungerade och sedan kom detta upp på andra varvet.

**Skärmbilder**
![image](https://user-images.githubusercontent.com/82646131/235237585-4179b5a6-2846-4eb7-926f-c14bb118d7a9.png)

**Browser :**
Firefox

**Comment by EndyMc** [comment]
Inget i konsolen

**Comment by EdwardKN** [comment]
online eller lokalt? @EndyMc

**Comment by EndyMc** [comment]
Lokalt

**Comment by EdwardKN** [comment]
Jag lyckas inte få buggen. 

Jag behöver veta om 
board.currentCard.owner == undefined, 
board.currentCard == board.boardPieces[players[turn].steps], 
board.auction == undefined,
players[turn].bot == undefined

**Comment by EndyMc** [comment]
Variablerna:
```
board.currentCard.owner == undefined
board.boardPieces[players[turn].steps] == undefined
board.auction == undefined
player[turn].bot == undefined
```

**Comment by EndyMc** [comment]
Hamnade på GÅ när jag kom in på det nya varvet, mycket möjligt att buggen är kopplad till det

**Comment by EdwardKN** [comment]
jag vet vad det är

**Comment by EdwardKN** [comment]
player.steps ska inte kunna vara mer än 40
