### ISSUE TITLE
Objekt på skärmen flyttas beroende på zoom-level

### ISSUE THREAD

**Issue by EndyMc** [EdwardKN/Monopoly#99]
**Förklara buggen**
När man är inne i en spelomgång och zoomar antingen in eller ut så flyttas allting på skärmen, de flyttas inte lika mycket, vilket bara gör problemet värre...

**Hur man återskapar buggen**
1. Skapa en ny match
2. Zooma ut eller in
4. Zooma tillbaka

**Hur det borde fungera**
Helst ska inget flyttas alls och ha fast positioner på skärmen.

**Browser :**
Firefox

**Comment by EdwardKN** [comment]
Denna går inte att lösa eftersom det är för att när du zoomar in så anpassar spelet sig till den nya upplösningen på canvasen och om den inte riktigt matchar vad spelet är gjort efter så kommer den ta den närmsta pixeln till det rätta. Anti aliasing löser detta problemet lite men den orsakar många andra problem istället.

**Comment by EndyMc** [comment]
![image](https://user-images.githubusercontent.com/82646131/235616468-7b394913-69bd-45c1-b4b7-4a687b7da62c.png)

**Comment by EdwardKN** [comment]
det där är ett annat problem

**Comment by EndyMc** [comment]
Det är samma problem, då det funkar vid vissa zoom-levlar, men inte andra
